In [3]:
import pandas as pd

archivo = 'C:/Users/ruso_/OneDrive/Escritorio/C5/cargofiveLCL/procesadorFCL/151896_Ibercondor_DRY_04-02-2025_FCL.xlsx'
hoja = 'ASIA OCEANIA - MED'

df_completo = pd.read_excel(archivo, sheet_name=hoja, header=None)

In [4]:
fila_encabezado_surcharges = None
for i in range(20):
    fila = df_completo.iloc[i].astype(str)
    if 'SUBJECT SURCHARGES:' in ' '.join(fila.values):
        fila_encabezado_surcharges = i
        print("Fila encontrada:", fila_encabezado_surcharges)
        break

if fila_encabezado_surcharges is None:
    raise ValueError("No se encontró el encabezado de surcharges en las primeras 20 filas.")

df_surcharges = pd.read_excel(
    archivo,
    sheet_name=hoja,
    header=fila_encabezado_surcharges
)

first_empty_row = 0
for index, row in df_surcharges.iterrows():
    if row.isna().all():
        first_empty_row = index
        break

df_surcharges = df_surcharges.iloc[:first_empty_row]

df_surcharges = df_surcharges.dropna(axis=1, how='all')

Fila encontrada: 13

In [5]:
df_surcharges

,SUBJECT SURCHARGES:,TYPE,INCLUDED OR SUBJECT,CURRENCY,AMOUNT,BASIS,Unnamed: 7
0,OBS (Asia/Oceania to Mediterranean) & India Su...,DRY,SUBJECT,USD,129,PER TEU,NaN
1,OBS (Asia/Oceania to Mediterranean) & India Su...,REEFER,SUBJECT,USD,243,PER TEU,NaN
2,EES (Asia/Oceania to Mediterranean),DRY,SUBJECT,USD,19,PER TEU,NaN
3,EES (India SubCont to Mediterranean),DRY,SUBJECT,USD,96,PER TEU,NaN
4,EES (Asia/Oceania to Mediterranean),REEFER,SUBJECT,USD,33,20RF,NaN
5,EES (Asia/Oceania to Mediterranean),REEFER,SUBJECT,USD,52,40RF,NaN
6,EES (India SubCont to Mediterranean),REEFER,SUBJECT,USD,187,20RF,NaN
7,EES (India SubCont to Mediterranean),REEFER,SUBJECT,USD,283,40RF,NaN
8,SCT,ALL,SUBJECT,USD,18,PER TEU,NaN
9,Emergency PSS,ALL,SUBJECT,USD,500,PER TEU,NaN
10,ESD (prepaid),ALL,SUBJECT,USD,35,PER BL,*this charge is payable by the freight payer p...
11,45'HC Additional NEU / MED TRADE,45',SUBJECT (if 45'),USD,700,UNIT / over HQ RATE,NaN
12,Heavy Weight Surcharge (Only applicable if it ...,ALL 20',AS PER COLUMN O,USD,300,UNIT,*Net Weight >= 16 tonnes
13,NaN,NaN,NaN,NaN,600,UNIT,*Net Weight >= 18 tonnes
14,GOH (hangers) SINGLE BAR,EQUIPMENT,SUBJECT (if hangers),USD,850,20',NaN
15,NaN,EQUIPMENT,SUBJECT (if hangers),USD,1220,40'DV &HQ,NaN
16,GOH (hangers) DOUBLE BAR,EQUIPMENT,SUBJECT (if hangers),USD,1100,20',NaN
17,NaN,EQUIPMENT,SUBJECT (if hangers),USD,1700,40'DV &HQ,NaN
18,SES (SPECIAL EQUIPMENT SURCHARGE),EQUIPMENT,SUBJECT (if IN GAUGE cargo),USD,375,20' FR / 20' OT,NaN
19,SES (SPECIAL EQUIPMENT SURCHARGE),EQUIPMENT,SUBJECT (if IN GAUGE cargo),USD,625,40' FR / 40' OT,NaN
20,IMO SURCHARGE (Except Fireworks),IMCO,SUBJECT (if DG cargo),USD,200,TEU,NaN
21,IMCO Surch group PSA1D/PSA2 (Excluding Fireworks),IMCO,SUBJECT (if DG cargo),USD,520,20',*PSA1 & PSA2 Applicable in all DG cargo origin...
22,IMCO Surch group PSA1D/PSA2 (Excluding Fireworks),IMCO,SUBJECT (if DG cargo),USD,728,40',NaN
23,IMO Surcharge group PSA1S/2A,IMCO,SUBJECT (if DG cargo),USD,416,20',NaN
24,IMO Surcharge group PSA1S/2A,IMCO,SUBJECT (if DG cargo),USD,572,40',NaN
25,IMO Surcharge group PSA2S/2B/2F,IMCO,SUBJECT (if DG cargo),USD,260,CNTR,NaN
26,IMO Surcharge group PSA3,IMCO,SUBJECT (if DG cargo),USD,0,TEU,NaN
27,War Risk Surcharge,ALL,"SUBJECT (applicable ex: United Arab Emirates, ...",USD,55,TEU,NaN

In [6]:
fila_encabezado_freights = None
for i in range(fila_encabezado_surcharges + 20, fila_encabezado_surcharges + 60):
    fila = df_completo.iloc[i].astype(str)
    if 'EFFECTVE DATE' in ' '.join(fila.values):
        fila_encabezado_freights = i
        break

if fila_encabezado_freights is None:
    raise ValueError("No se encontró el encabezado de freights en el rango esperado.")
else:
    print("Fila encontrada:", fila_encabezado_freights)

Fila encontrada: 44

In [8]:
df_freights = pd.read_excel(
    archivo,
    sheet_name=hoja,
    header=fila_encabezado_freights
)
df_freights = df_freights.dropna(axis=1, how='all')

In [9]:

df_freights

,EFFECTVE DATE,EXPIRY DATE,SERVICE SCOPE,CODE,ORIGIN,DESTINATION,CARGO,T/S PORT,SERVICE,CUR.,20,40,HC,INCLUDE SURCHARGES
0,2025-01-19,2025-02-15,AMW,CNNGB,"NINGBO, ZHEJIANG",ALGECIRAS,Dry General,KRPUS,FE4,USD,2210.0,3150.0,3150,"CAF,CSS,LSF,HEA"
1,2025-01-19,2025-02-15,AMW,CNSHA,"SHANGHAI, SHANGHAI",ALGECIRAS,Dry General,NaN,FE4,USD,2210.0,3150.0,3150,"CAF,CSS,LSF,HEA"
2,2025-01-19,2025-02-15,AMW,CNTAO,"QINGDAO, SHANDONG",ALGECIRAS,Dry General,NaN,FE4,USD,2210.0,3150.0,3150,"CAF,CSS,LSF,HEA"
3,2025-01-19,2025-02-15,AMW,CNTXG,XINGANG,ALGECIRAS,Dry General,NaN,FE4,USD,2210.0,3150.0,3150,"CAF,CSS,LSF,HEA"
4,2025-01-19,2025-02-15,AMW,CNYTN,"YANTIAN, GUANGDONG",ALGECIRAS,Dry General,NaN,NaN,USD,2210.0,3150.0,3150,"CAF,CSS,LSF,HEA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,2025-01-19,2025-01-31,WMW,PKKHI,KARACHI,ALGECIRAS,Reefer,NaN,IOM,USD,1460.0,NaN,1520,"CAF,CSS"
190,2025-01-19,2025-01-31,WMW,PKKHI,KARACHI,BARCELONA,Dry General,NaN,IOM,USD,980.0,300.0,300,"CAF,CSS"
191,2025-01-19,2025-01-31,WMW,PKKHI,KARACHI,BARCELONA,Reefer,NaN,IOM,USD,1460.0,NaN,1520,"CAF,CSS"
192,2025-01-19,2025-01-31,WMW,PKKHI,KARACHI,VALENCIA,Dry General,NaN,IOM,USD,980.0,300.0,300,"CAF,CSS"
193,2025-01-19,2025-01-31,WMW,PKKHI,KARACHI,VALENCIA,Reefer,NaN,IOM,USD,1460.0,NaN,1520,"CAF,CSS"